
const chainDifference = {
  Cosmos: {
    firstLink: 'proxy',
    secondLink: '/cosmoshub-lcd',
    blockFirstLink: 'proxy',
    blockSecondLink: '/cosmoshub-rpc',
    unit: 'uatom',
    secondUnit: 'atom',
    unitDivision: 1000000,
    iconLink: 'atom.svg',
    relayer: 'cosmoshub-4',
  },
  Injective: {
    firstLink: 'proxy',
    secondLink: '/inj-lcd',
    blockFirstLink: 'proxy',
    blockSecondLink: '/inj-rpc',
    unit: 'inj',
    secondUnit: 'inj',
    unitDivision: 1000000000000000000,
    iconLink: 'injective.png',
    relayer: 'injective-1',
  },
  Band: {
    firstLink: 'proxy',
    secondLink: '/band-lcd',
    blockFirstLink: 'proxy',
    blockSecondLink: '/band-rpc',
    unit: 'uband',
    secondUnit: 'band',
    unitDivision: 10000000,
    iconLink: 'band.svg',
    relayer: 'laozi-mainnet',
  },
  Juno: {
    firstLink: 'proxy',
    secondLink: '/juno-lcd',
    blockFirstLink: 'proxy',
    blockSecondLink: '/juno-rpc',
    unit: 'ujuno',
    secondUnit: 'juno',
    unitDivision: 1000000,
    iconLink: 'juno.svg',
    relayer: 'juno-1',
  },
  Kava: {
    firstLink: 'proxy',
    secondLink: '/kava-lcd',
    blockFirstLink: 'proxy',
    blockSecondLink: '/kava-rpc',
    unit: 'ukava',
    secondUnit: 'kava',
    unitDivision: 1000000,
    iconLink: 'kava.png',
    relayer: 'kava_2222-10',
  },
  Stride: {
    firstLink: 'proxy',
    secondLink: '/stride-lcd',
    blockFirstLink: 'proxy',
    blockSecondLink: '/stride-rpc',
    unit: 'ustrd',
    secondUnit: 'strd',
    unitDivision: 1000000,
    iconLink: 'strd.svg',
    relayer: 'stride-1',
  },
  Kujira: {
    firstLink: 'proxy',
    secondLink: '/kujira-lcd',
    blockFirstLink: 'proxy',
    blockSecondLink: '/kujira-rpc',
    unit: 'ukuji',
    secondUnit: 'kuji',
    unitDivision: 1000000,
    iconLink: 'kujira.png',
    relayer: 'kaiyo-1',
  },
  Akash: {
    firstLink: 'proxy',
    secondLink: '/akash-lcd',
    blockFirstLink: 'proxy',
    blockSecondLink: '/akash-rpc',
    unit: 'uakt',
    secondUnit: 'akt',
    unitDivision: 1000000,
    iconLink: 'akt.svg',
    relayer: 'akashnet-2',
  },
  Osmosis: {
    firstLink: 'proxy',
    secondLink: '/osmo-lcd',
    blockFirstLink: 'proxy',
    blockSecondLink: '/osmo-rpc',
    unit: 'uosmo',
    secondUnit: 'osmo',
    unitDivision: 1000000,
    iconLink: 'osmosis.svg',
    relayer: 'osmosis-1',
  },
  Stride: {
    firstLink: 'proxy',
    secondLink: '/stride-lcd',
    blockFirstLink: 'proxy',
    blockSecondLink: '/stride-rpc',
    unit: 'ustrd',
    secondUnit: 'strd',
    unitDivision: 1000000,
    iconLink: 'strd.svg',
    relayer: 'stride-1',
  },

} 


export default chainDifference