
const chainDifference = {
  Cosmos: {
    firstLink: 'cosmos.lcd',
    secondLink: '',
    blockFirstLink: 'cosmos.rpc',
    blockSecondLink: '',
    unit: 'uatom',
    secondUnit: 'atom',
    unitDivision: 1000000,
    iconLink: 'atom.svg',
    relayer: 'cosmoshub-4',
  },
  Injective: {
    firstLink: 'proxy',
    secondLink: '/inj-lcd',
    blockFirstLink: 'proxy',
    blockSecondLink: '/inj-rpc',
    unit: 'inj',
    secondUnit: 'inj',
    unitDivision: 1000000000000000000,
    iconLink: 'injective.png',
    relayer: 'injective-1',
  },
  Band: {
    firstLink: 'proxy',
    secondLink: '/band-lcd',
    blockFirstLink: 'proxy',
    blockSecondLink: '/band-rpc',
    unit: 'uband',
    secondUnit: 'band',
    unitDivision: 10000000,
    iconLink: 'band.svg',
    relayer: 'laozi-mainnet',
  },
  Juno: {
    firstLink: 'proxy',
    secondLink: '/juno-lcd',
    blockFirstLink: 'proxy',
    blockSecondLink: '/juno-rpc',
    unit: 'ujuno',
    secondUnit: 'juno',
    unitDivision: 1000000,
    iconLink: 'juno.svg',
    relayer: 'juno-1',
  },
  Kava: {
    firstLink: 'proxy',
    secondLink: '/kava-lcd',
    blockFirstLink: 'proxy',
    blockSecondLink: '/kava-rpc',
    unit: 'ukava',
    secondUnit: 'kava',
    unitDivision: 1000000,
    iconLink: 'kava.png',
    relayer: 'kava_2222-10',
  },
} 


export default chainDifference